# Generated by Django 3.0.6 on 2020-08-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=90, verbose_name='Titulo de tarea')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('asignatura', models.CharField(max_length=60, verbose_name='Asignatura')),
                ('fecha_entrega', models.DateField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('nivel', models.IntegerField(verbose_name='Nivel de Complejidad')),
            ],
        ),
    ]
