# Generated by Django 3.0.6 on 2020-08-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='fecha_entrega',
            field=models.DateField(verbose_name='Fecha de Entrega'),
        ),
    ]
