# Generated by Django 3.0.6 on 2020-08-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200810_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='material',
            field=models.FileField(max_length=200, null=True, upload_to='material/', verbose_name='Material de apoyo'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='descripcion',
            field=models.TextField(max_length=500, null=True, verbose_name='Descripción'),
        ),
    ]
