# Generated by Django 3.0.6 on 2020-08-10 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20200810_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='nivel',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Nivel de Complejidad (1 = Muy fácil ~ 5 = Muy difícil)'),
        ),
    ]
