# Generated by Django 3.0.6 on 2020-08-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20200810_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='material',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='material/', verbose_name='Material de apoyo'),
        ),
    ]
